parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
  JagaadTask\Components\Musement\Client:
    public: true
    arguments:
      $baseUri: '%MUSEMENT_BASE_URI%'

  JagaadTask\Components\Musement\Transformer\ResponseTransformer:
  JagaadTask\Components\Musement\Factory\CityFactory:

  GuzzleHttp\ClientInterface:
    class: GuzzleHttp\Client

